### ISSUE TITLE
Problems with color macros

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax-demos-web#10]
This probably falls into the "not yet implemented" category, but just in case it doesn't...
[just noticed message saying color.js isn't implemented for V3, but see bottom when it is]

With 
```
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<script src="https://cdn.rawgit.com/mathjax/mj3-demos/3.0.0-beta.1/mj3-tex2html-beta.dist.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { extensions: ["color.js"] }});
</script>
```
in the header and this horrible mess in the body,
```
$$ 
\color{#00B219}{\bf{8}}
\color{#adadad}{(}
\bf{\color{#ff8000}{-}}
6
\,\colorbox{#e5ff00}{\(\mkern{-7mu}+\mkern{-6mu}\)}\,
2
\color{#adadad}{)}
\,\colorbox{#9100ff}{\(\mkern{-7mu}\div\mkern{-6mu}\)}\,
\color{#ff0040}{\bf{3}}
\;\color{#adadad}{=}
$$
```
I get "You can't use 'macro parameeter character #' in math mode".

Rendering in V2 was (IMHO) less than perfect, but it conveyed the idea I wanted to. The two weirdnesses are that the `-` and `=` seem much wider than they should be and that the parens aren't close to symmetric:
![image](https://user-images.githubusercontent.com/1545836/41795093-70cb1646-7616-11e8-810d-8c3847e67ad9.png)

```

**Comment by pkra** [comment]
From https://github.com/mathjax/mj3-demos/blob/ea8f2770a67a8c83ff9839bb806aed6baf1fd366/README.md#whats-included

> For example, \unicode, \bbox, and the color extension are not yet available.

IIRC, the plan is to move the color extension into the core. The old core's color macros were not faithful to TeX and the old color extensions fixed that; v3 finally allows to change that.

**Comment by dpvc** [comment]
@NSoiffer, I just found out that I'm not receiving email notifications from this issue list, and that you had made several bug reports last year!  I am only just seeing them now for the first time.  So sorry for missing your messages.

I know it is too late, but just to answer this for anyone looking:

>  The two weirdnesses are that the - and = seem much wider than they should be and that the parens aren't close to symmetric

The reason that the parentheses are not symmetric is because if the `\bf` macro in the third line.  Note that `\bf` does not take an argument, but is a switch, so everything after that is in bold, not just the stuff in braces after it (for that, use `\mathbf{...}`).  So the open parenthesis is non-bold, but the closing one is bold.  That accounts for the difference in them.

The wideness of the minus and equals is also affected by that, since they are both bold as well.  I think that may be what you are noticing.

Again, sorry about not seeing this when you sent it.  I have turned on email for the issue tracker, and don't know why it wasn't on originally.
