### ISSUE TITLE
"npm run make-custom-tex-extension"   is not working

### ISSUE THREAD

**Issue by kimdohyung5** [mathjax/MathJax-demos-web#26]
Hi there.

after I read this page "https://github.com/mathjax/MathJax-demos-web/blob/master/custom-tex-extension/mml.html.md"
I run "npm install" command in the downloaded MathJax-demos-web folder.
then, I got this message.

---------------------------------------------------------------
found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
---------------------------------------------------------------

and I run "npm run make-custom-tex-extension " then,
---------------------------------------------------------------------------------------------------------------------------------
> MathJax-demos-web@3.0.5 make-custom-tex-extension E:\ai\nodejs\MathJax-demos-web\ttt\MathJax-demos-web
> cd custom-tex-extension && node ../node_modules/mathjax-full/components/bin/pack

Command failed: npx webpack --display-modules
---------------------------------------------------------------------------------------------------------------------------------

so, I want to make the "mml.min.js" file but, I could not do that. so Please help me.
I run on windows 10 , with node : v12.18.0

**Comment by dpvc** [comment]
Try changing the `package.json` file so that the `devDependencies` are

```
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/preset-env": "^7.11.0",
    "babel-loader": "^8.1.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  },
```

There seems to be a version problem with `babel-loader` now looking for the `@babel` versions rather than the older `babel-` ones.  I suppose that may be what the `package-lock.json` would have prevented (I never really understood that file's purpose).

**Comment by kimdohyung5** [comment]
I tried as you said. but, It didn't work.

after I changed the package.json as you sugested, I got the same error message that i'd seen before.
--------------------------------------------------------------------------------------------------------------
**found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details**
--------------------------------------------------------------------------------------------------------------

when I typed out according to error message instruction, I found that "uglifyjs-webpack-plugin" which mathjax-full package is using is old and outdated. 

so Could you please show me another way to install this demo app install properly?

belows are error message I found when typed "npm audit"

------------------------------------------------------------------------------------------------------------
E:\ai\contentsmake\webdemo\aaa\MathJax-demos-web>npm audit

                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Moderate        Cross-Site Scripting

  Package         serialize-javascript

  Patched in      >=2.1.1

  Dependency of   uglifyjs-webpack-plugin [dev]

  Path            uglifyjs-webpack-plugin > serialize-javascript

  More info       https://npmjs.com/advisories/1426


  High            Remote Code Execution

  Package         serialize-javascript

  Patched in      >=3.1.0

  Dependency of   uglifyjs-webpack-plugin [dev]

  Path            uglifyjs-webpack-plugin > serialize-javascript

  More info       https://npmjs.com/advisories/1548

found 2 vulnerabilities (1 moderate, 1 high) in 546 scanned packages
  2 vulnerabilities require manual review. See the full report for details.
---------------------------------------------------------------------------------------------------------


Thank you.

**Comment by dpvc** [comment]
Yes, the uglify plugin is the source of the warnings (it will be replaced by the `terser-webpack-plugin` in the next release), but the issues in the audit are for when `serialize-javascript` is included as part of the package that is being used in the browser (when user-provided information is being passed to it).  That is not the case, here, as the webpacked file you obtain only includes MathJax code, not the serialize-javascript code.  While the message is alarming, it is not actually pertinent to the usage here.  With the new list of files that I gave you, you should be able to build the extension despite this warning.

Although you could replace the `uglifyjs-webpack-plugin` with `terser-webpack-plugin` to avoid the messages, you would also have to modify the `node_modules/mathjax-full/components/webpack.config.js` to use the new plugin instead of the old one.  That can be done, but is more complicated, and not necessary to build the extension, so I didn't suggest that.

**Comment by kimdohyung5** [comment]
as you commented, I tried with terser-webpack-plugin and got the output "mml.min.js", but didn't worked properly.
so, I think I better hope that next release would be out soon.

**Comment by dpvc** [comment]
Version 3.1 is out, so you should be able to do the build.
