### ISSUE TITLE
"npm run make-custom-tex-extension" is still not  working.

### ISSUE THREAD

**Issue by kimdohyung5** [mathjax/MathJax-demos-web#30]
a few months ago, I issued this. and checked that this is resolved, but unfortunately, it is not working.
When I typed this command "npm run make-custom-tex-extension" , I found that the file "mml.min.js" with this logs.

---------------------------------------------------------------------------------------------------
npm run make-custom-tex-extension

> MathJax-demos-web@3.0.5 make-custom-tex-extension E:\ai\nodejs\MathJaxNodeTest\MathJax-demos-web
> cd custom-tex-extension && node ../node_modules/mathjax-full/components/bin/pack

Hash: 640e2f14a8f1dd014edf
    Version: webpack 4.44.2
    Time: 1084ms
    Built at: 2020-11-25 8:07:40 ├F10: PM┤
         Asset     Size  Chunks             Chunk Names
    mml.min.js  113 KiB       0  [emitted]  main
    Entrypoint main = mml.min.js
     [0] E:\ai\nodejs\MathJaxNodeTest\MathJax-demos-web/node_modules/mathjax-full/js/core/MmlTree/MmlNode.js 28.6 KiB {0} [built]
     [1] E:\ai\nodejs\MathJaxNodeTest\MathJax-demos-web/node_modules/mathjax-full/js/input/tex/TexError.js 1.68 KiB {0} [built]
.........................................
.........................................
........................................
     [23] E:\ai\nodejs\MathJaxNodeTest\MathJax-demos-web/node_modules/mathjax-full/js/input/tex/Stack.js 4.13 KiB {0} [built]
    [24] E:\ai\nodejs\MathJaxNodeTest\MathJax-demos-web/node_modules/mathjax-full/js/input/tex/Symbol.js 1.73 KiB {0} [built]
---------------------------------------------------------------------------------------------------------------------------------------

I think that that file "mml.min.js" created is too big to be working compared to original mml.min.js you distributed.
that file's size created was 113KB.

 when i opened the mml.html, then i found that paper's not working.
 so any guide would you please to suggest to me?

**Comment by dpvc** [comment]
This is due to the fact that Windows uses backslashes as directory separators rather than forward slashes like everybody else.  So the webpack configuration that looks for shared library files is not recognizing them and including everything rather than patching in the shared versions.

I'll have to look into how to make it work with Windows paths as well as unix paths.

**Comment by dpvc** [comment]
I've made a pull request to MathJax-src that fixers the problem.  You could resolve it now by getting the copy of [`webpack.common.js`](https://github.com/mathjax/MathJax-src/blob/c75cbb6d39302338fab28123b2fec8906f3d9379/components/webpack.common.js) from that PR and using it to replace the one in `node_modules\mathjax-full\components` in your copy of `MathJax-demos-web`.

While checking on this, I also found that I had failed to push some updates to the `MathJax-demos-web` repository that were part of the v3.1.2 update, so I've pushed those and tagged the release.  You might want to fetch the changes to the demos and do `npm install` again (since the dependencies have changed), in addition to updating the webpack configuration file from the PR.  Note that you should update `webpack.common.js` *after* doing `npm install` or you will lose the update.

**Comment by kimdohyung5** [comment]
Thank you,  It works.!!!!

I can run "npm run make-custom-tex-extension" on my windows pc.

**Comment by dpvc** [comment]
Glad to hear that it works for you.  Thanks for the confirmation.
