### ISSUE TITLE
Building a custom Tex extension crashes.

### ISSUE THREAD

**Issue by simurgh9** [mathjax/MathJax-demos-web#31]
I was following along the demo [here](https://github.com/mathjax/MathJax-demos-web/tree/master/custom-tex-extension) and [here](https://docs.mathjax.org/en/latest/web/webpack.html#a-custom-extension).

1. I make a directory: `hwjax`. Then I start a `package.json` through `npm init`. Oh, `npm --version` returns `6.14.10` and `node --version` returns `v12.19.0`. The `package.json` contains:

```json
{
  "name": "hwjax",
  "version": "0.0.1",
  "description": "Mathjax extension for homework Latex class.",
  "main": "homework.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "mathjax",
    "latex",
    "homework"
  ],
  "author": "Simurgh",
  "license": "GPL-3.0-or-later"
}
```
2. Now running `npm install mathjax-full webpack webpack-cli terser-webpack-plugin babel-loader @babel/core @babel/preset-env` produces:

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN hwjax@0.0.1 No repository field.

+ babel-loader@8.2.2
+ @babel/preset-env@7.12.11
+ terser-webpack-plugin@5.0.3
+ @babel/core@7.12.10
+ webpack@5.11.1
+ webpack-cli@4.3.1
+ mathjax-full@3.1.2
added 278 packages from 184 contributors and audited 278 packages in 11.236s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

3. Right so now I assume we have everything. I get the files [mml.js](https://raw.githubusercontent.com/mathjax/MathJax-demos-web/master/custom-tex-extension/mml.js) and [webpack.config.js](https://raw.githubusercontent.com/mathjax/MathJax-demos-web/master/custom-tex-extension/webpack.config.js). Listing files in `hwjax/` produces: `mml.js  node_modules  package.json  package-lock.json  webpack.config.js`. Note that I fixed the paths in the webpack configs:

```js
const PACKAGE = require('./node_modules/mathjax-full/components/webpack.common.js');

module.exports = PACKAGE(
    'mml',                                // the package to build
    './node_modules/mathjax-full/js',    // location of the MathJax js library
    [                                     // packages to link to
        'components/src/core/lib',
        'components/src/input/tex-base/lib'
    ],
    __dirname,                            // our directory
    '.'                                   // dist directory
);
```

4. Now I don't think I need an `npm install` but I do it anyways since the documentation asks for it. At this point, I don't expect `npm run make-custom-tex-extension` to work because the `package.json` does not define any scripts.

```shell
npm ERR! missing script: make-custom-tex-extension

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tsfn/.npm/_logs/2020-12-31T23_12_20_164Z-debug.log
```

Now I run `node node_modules/mathjax-full/components/bin/makeAll` which produces:

```shell
[snip]
Building /src/ui/menu
    
Building /src/ui/safe
    
Webpacking /path/to/hwjax
    Command failed: npx webpack --display-modules
Webpacking /src/a11y/assistive-mml
    Command failed: npx webpack --display-modules
Webpacking /src/a11y/complexity
[snip]
```
5. Here is the summary of the setup:

```shell
.../hwjax$ npm --version && node --version && npx webpack --version && tree -L 1
6.14.10
v12.19.0
webpack 5.11.1
webpack-cli 4.3.1
.
├── mml.js
├── node_modules
├── package.json
├── package-lock.json
└── webpack.config.js

1 directory, 4 files
```

**Comment by dpvc** [comment]
> The github link asks you to do:
> 
>     npm install
>     npm run make-custom-tex-extension
> 
> Which does not work.

Can you be more specific about what "does not work"  means in this case?  Did you did that from the main directory (not the subdirectory)?

> The docs asks you to run `node ../node_modules/mathjax-full/components/bin/makeAll`

That is because the version in the [documentation](https://docs.mathjax.org/en/latest/web/webpack.html#a-custom-extension) does not have a `package.json` to define the script for `npm run`.  Note that `npm run make-custom-tex-extension` simply cds to the extension directory and then does the `node ../node_modules/mathjax-full/components/bin/pack`, which is the only part of `makeAll` that is needed.

Can you verify the web pack version using

```
npx webpack --version
```

and see what you get?`

It sounds like you are working in a directory that doesn't have the packages installed.  Where is the `package.json` file in relation to the component directory?  You seem to be working in `.../Homework/hwjax`; is the `package.json` file in the `Homework` directory or the `hwjax` directory?  If the latter, then you should be using `node node_modules/mathjax-full/components/bin./makeAll` without the `../`.  If the node packages are correctly installed, you would not get the message about needing to install `webpack-cli`.

The best I can say is check the installation because that seems to be the issue.  You might try removing the `node_modules` directory entirely and reinstalling.  You could also use `npm list` to see what is installed.

Finally, you might indicate the contents of your `hwjax` directory, and in particular the `webpack.config.js` file that it contains.

**Comment by simurgh9** [comment]
> Can you be more specific about what "does not work" means in this case? Did you did that from the main directory (not the subdirectory)?

Yes. How could it work anyways? I started a `package.json` with `npm init`. It had no scripts property so how could we do anything resembling `npm run <script name>`? The error I get is that there are no such scripts.

> That is because the version in the documentation does not have a package.json to define the script for npm run

Yes, exactly!

> Note that npm run make-custom-tex-extension simply cds to the extension directory ...

I apologise, I am not a seasoned np* and javascript developer. I am not sure how could I note that while I don't know where that script even is?

> Can you verify the web pack version using

Will update. But don't the dependencies JSON object answer this? `"webpack": "^5.11.1"`.

Let me do a fresh install and I'll update my issue to answer the rest of your questions.

**Comment by simurgh9** [comment]
Okay so I decided to take a look around in `node_modules/mathjax-full/components/bin./makeAll` and found the following function,

```js
/**
 * Run webpack if there is a configuration file for it
 *
 * @param {string} dir   The directory to check
 */
function webpackLib(dir) {
  const file = path.join(dir, 'webpack.config.js');
  if (!fs.existsSync(file)) return;
  console.info('Webpacking ' + dir.replace(compRE, ''));
  const wd = process.cwd();
  try {
    process.chdir(dir);
    const result = execSync('npx webpack --display-modules');
    console.info('    ' + String(result).replace(/\n/g, '\n    ')
                 .replace(/ \.\.\//g, ' ' + path.dirname(path.resolve(dir)) + '/')
                 .replace(compRE, '[components]')
                 .replace(rootRE, '[js]')
                 .replace(nodeRE, '[node]'));
  } catch (err) {
    console.info('    ' + err.message);
  }
  process.chdir(wd);
}
```

Seems to me that the one thing that is strange is the line `const result = execSync('npx webpack --display-modules');`. I tried looking at `npx webpeack -help=verbose` and could not find the option `--display-modules` anywhere! I changed that line to `const result = execSync('npx webpack');` and now "webpacking" the package I defined works (or so I think...),

```shell
Building /src/ui/safe
    
Webpacking /path/to/hwjax
    
Webpacking /src/a11y/assistive-mml
    Command failed: npx webpack
Webpacking /src/a11y/complexity
    Command failed: npx webpack
```
The other "webpackings" still fail though. I do however get an `mml.min.js`. Is that all we need? Should I worry about the rest failing?

**Comment by dpvc** [comment]
> Yes. How could it work anyways?

It was not clear that you were creating your own extension.  It looked like you might be trying to build the one in this repository.  One would not normally use `npm run` on a fresh `package.json` that doesn't contain any scripts.

> I am not sure how could I note that while I don't know where that script even is?

It is in the `package.json` file, which is where all the `npm` information is stored.  I believe that `npm run` also lists the commands that it performs unless you use the `--silent` option.

> But don't the dependencies JSON object answer this?

That says what the version *should* be.  But I'm trying to determine the version that is actually running.  Since the error messages seem to indicate that not all the node modules listed in the dependencies have been installed, I am trying to verify that you are running the actual version request in the dependencies.  That's also why I am asking about the contents of the directory you are working in.  

>  I tried looking at `npx webpeack --help=verbose` and could not find the option `--display-modules` anywhere!

That makes me wonder about the version you are actually running.  It may be that the option is added by the `webpack-cli` module, and if that isn't installed, that might be why it doesn't show up.  But I don't think you can run `--help` without `webpack-cli`, so that suggests you might be getting a different version of `webpack` than the one you think you are.

> I changed that line to ... and now "webpacking" the package I defined works (or so I think...),

The messages you are getting seem strange.  You should not be building or packing items from `/src`, just your extension.  Try running the `pack` command rather than `makeAll` (you will probably need to remove `---display-modules` there as well).

Note that the example extension in this repository is in a subdirectory of the main directory that contains the `node_modules` directory.  Because `makeAll` will recursively make all the subdirectories, if the `node_modules` directory is in the same directory where you are running `makeAll`, it will probably try to make the files in the `mathjax-full` directory.  That is not needed, and seems to be causing errors in any case.
Running just `pack` should be enough, since that is non-recursive.

Again, the contents of your directory would help, as well as the contents of the `webpack.config.js` file for your extension.

**Comment by simurgh9** [comment]
> It was not clear that you were creating your own extension. It looked like you might be trying to build the one in this repository.

I am writing my own extension, I planed on making it work by copying the code from the demo extension and then changing it once the project was setup.

> Again, the contents of your directory would help, as well as the contents of the webpack.config.js file for your extension.

I did show them both, did you look at the updated issue body?

**Comment by pkra** [comment]
At the risk of not actually helping, [here's an extension I wrote a while back](https://github.com/krautzource/mathjax-aria-label/) - though @dpvc later poined out that my method of loading it into MathJax is not support. I simply transpile the TS of the extension into an ES module and adjust the require calls "by hand".

**Comment by simurgh9** [comment]
The documentation and this repository cross reference each other as though they do exactly the same thing which is a bit confusing in my opinion. Since I was able to build my package by removing that option, I will close this issue for now. If anyone cares to look at what I ended up with [here](https://github.com/simurgh9/homework/tree/master/src/mathjax) it is. Oh, and thank you @pkra!

**Comment by dpvc** [comment]
> I did show them both, did you look at the updated issue body?

No.  I get messages about new comments, but not about updates to existing posts.  In order to keep the history of the conversion intact, it is unusual to make major revisions to the original post, so I didn't look there.  I expected that my question would have been answered in a new comment.  Sorry to have missed your update.  Glad you were able to get it to work in the end, however.
