### ISSUE TITLE
XSS vulnerabilities

### ISSUE THREAD

**Issue by donno2048** [mathjax/MathJax-demos-web#34]
Even if it's not an official site or anything why would you leave it open to XSS attacks? I mean on https://mathjax.github.io/MathJax-demos-web/input-tex_mml2chtml.html
Even the easy
```html
<img src=x onerror="alert(document.domain)"/>
```

Would work and in fact, even in the "official" mathjax usage there are some XSS vulnerabilities, for example, sympy has an XSS vulnerability in its mathjax "interpreter" sympy/sympy-live#192

**Comment by dpvc** [comment]
I don't believe the page you link is open to XSS attacks.  While it is true that you yourself can enter such an image tag into the input area, the page does not initialize the input area with data from the URL parameters, so you can not create the kind of nefarious URL that you describe in the sympy issue that you site.  (Also, that issue with the `\unicode` macro was resolve, as you seem to have found out, as your solution there was to update the version of MathJax, though I don't see why you suggested 2.7.4 rather than 2.7.9, the current highest version of v2.)

If you have something else in mind, could you be more specific?
